name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main 

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    # Set up Docker
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_IMAGE_NAME }} .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_IMAGE_NAME }}

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
    
    - name: SSH into EC2 and update Docker container
      uses: appleboy/ssh-action@v0.1.1
      with:
          debug: true  # Enable debug mode for more detailed SSH logs
          host: ${{ secrets.EC2_HOST }}  # EC2 host IP or DNS
          username: ubuntu  # EC2 instance username
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Use the private key from GitHub Secrets
          script: |
            docker pull ${{ secrets.DOCKER_IMAGE_NAME }}
            docker stop my_container || true
            docker rm my_container || true
            docker run -d --name my_container -p 3000:3000 ${{ secrets.DOCKER_IMAGE_NAME }}
      